version: '2'
volumes:
  drupal-sites:
  drupal-data:
services:
  drupal:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - drupal-sites:/temporary/sites
    ports:
      - 8080:80
  postgres:
    image: postgres:latest
    volumes:
      - drupal-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pwd